import type { AppConfig } from '../src/shared/config/environment.js';
import type { RuntimeInfo } from '../src/modules/system/system.types.js';

export const testConfig: AppConfig = {
  appEnvironment: 'test',
  appVersion: '0.1.0',
  commitSha: 'test-sha',
  buildTime: '2026-07-12T10:00:00.000Z',
  port: 4000,
  mongodbUri: 'mongodb://localhost:27017/microlearning-test?replicaSet=rs0',
  publicWebUrl: 'http://localhost:3000',
  allowedOrigins: ['http://localhost:5173'],
  accessTokenSecret: 'synthetic-access-token-secret-for-test-fixture',
  accessTokenIssuer: 'microlearning-api',
  accessTokenAudience: 'microlearning-web',
  accessTokenTtlSeconds: 900,
  refreshTokenTtlSeconds: 604_800,
  refreshReuseGraceSeconds: 5,
  refreshCookieName: 'ml_refresh',
  refreshCookieSecure: false,
  authIdentityPepper: 'synthetic-identity-pepper-for-test-fixture',
  teacherInvitationTtlDays: 7,
  classroomCodePepper: 'synthetic-classroom-code-pepper-for-test-fixture',
  classroomCodeLength: 8,
  classroomInviteTokenBytes: 32,
  classroomInviteDefaultTtlDays: 30,
  classroomRateLimits: {
    joinIpMax: 20,
    joinIdentityMax: 10,
    joinWindowSeconds: 900,
    previewIpMax: 30,
  },
  rateLimits: {
    windowSeconds: 900,
    registerMax: 10,
    loginMax: 30,
    refreshMax: 60,
    publicInvitationMax: 20,
    adminInvitationWindowSeconds: 3600,
    adminInvitationMax: 20,
    loginFailureWindowSeconds: 900,
    loginFailureMaxAttempts: 5,
    loginCooldownSeconds: 900,
  },
  bootstrapAdminEnabled: false,
  logLevel: 'silent',
};

export const testRuntimeInfo: RuntimeInfo = {
  appName: 'Microlearning Classroom LMS API',
  version: testConfig.appVersion,
  environment: testConfig.appEnvironment,
  commitSha: testConfig.commitSha,
  buildTime: testConfig.buildTime,
};
