import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    exclude: ['tests/integration/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/server.ts',
        'src/**/*.model.ts',
        'src/**/*.repository.ts',
        'src/types/**',
        // Transactional orchestration is measured by the real Mongo integration coverage gate.
        'src/modules/phase-three.router.ts',
        'src/modules/bootstrap/phase-three-demo-seed.service.ts',
        'src/modules/bootstrap/phase-four-demo-seed.service.ts',
        'src/modules/classroom-credentials/classroom-credential.service.ts',
        'src/modules/classrooms/classroom-ownership.reader.ts',
        'src/modules/classrooms/classroom.domain.ts',
        'src/modules/classrooms/classroom.dto.ts',
        'src/modules/classrooms/classroom.service.ts',
        'src/modules/enrollment-policy/enrollment-policy.service.ts',
        'src/modules/enrollments/enrollment.service.ts',
        'src/modules/courses/course.service.ts',
        'src/modules/courses/course-governance.service.ts',
        'src/modules/announcements/announcement.service.ts',
        'src/modules/deadlines/lesson-deadline.service.ts',
        'src/modules/flashcards/flashcard.service.ts',
        'src/modules/lessons/lesson.service.ts',
        'src/modules/learning-progress/student-learning.service.ts',
        'src/modules/learning-progress/teacher-course-dashboard.service.ts',
        'src/modules/content-governance/classroom-content.repository-reader.ts',
        'src/modules/modules/module.service.ts',
        'src/modules/phase-four.router.ts',
        'src/modules/phase-five.router.ts',
        'src/modules/bootstrap/phase-five-demo-seed.service.ts',
        'src/modules/assignments/assignment.service.ts',
        'src/modules/deadline-exceptions/deadline-exception.service.ts',
        'src/modules/grades/grade.service.ts',
        'src/modules/learning-progress/mongo-learning-activity.reader.ts',
        'src/modules/quizzes/quiz.service.ts',
        'src/modules/questions/question.service.ts',
        'src/modules/quiz-attempts/quiz-attempt.service.ts',
        'src/modules/quiz-attempts/quiz-review.service.ts',
        'src/modules/submissions/submission.service.ts',
        // Phase 06 Mongo adapters and rebuild orchestration are exercised by replica-set suites
        // and command evidence; pure reporting contracts and policies remain in unit coverage.
        'src/modules/phase-six.foundation.ts',
        'src/modules/reporting/adapters/**',
        'src/modules/reporting/reporting-refresh.service.ts',
        'src/scripts/reporting-*.ts',
        'src/shared/database/index-compatibility.ts',
        'src/shared/database/phase-five-migration.ts',
        'src/shared/database/phase-six-indexes.ts',
        'src/shared/database/phase-six-migration.ts',
        'src/shared/database/phase-four-indexes.ts',
        'src/shared/database/phase-three-indexes.ts',
      ],
      thresholds: {
        statements: 75,
        branches: 45,
        functions: 70,
        lines: 75,
      },
    },
  },
});
